tango_with_django_project/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include
from django.conf import settings
from django.conf.urls.static import static
from tenrr import views

urlpatterns = [
    path('', views.index, name='index'),
    path('tenrr/', include('tenrr.urls')),
    path('admin/', admin.site.urls),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

tenrr/urls.py
from django.urls import path
from tenrr import views
from .views import like_post
from .views import my_profile, edit_profile

app_name = 'tenrr'

urlpatterns = [
    path('', views.index, name='index'),
    path('post/', views.post, name='post'),
    path('search/', views.search, name='search'),
    path('about/', views.about, name='about'),
    path('recommendations/', views.recommendations, name='recommendations'),
    path('login/', views.login_view, name='login'),
    path('signup/', views.signup_view, name='signup'),
    path('logout/', views.logout_view, name='logout'),
    path('edit_profile/', views.edit_profile, name='edit_profile'),
    path('like_post/<int:post_id>/', views.like_post, name='like_post'),
    path('my_profile/', views.my_profile, name='my_profile'),
    path('delete_post/<int:post_id>/', views.delete_post, name='delete_post'),
    path('buy_post/<int:post_id>/', views.buy_post, name='buy_post'),
    path('confirm_purchase/<int:post_id>/', views.confirm_purchase, name='confirm_purchase'),
    path('complete_sale_page/<int:purchase_id>/', views.complete_sale_page, name='complete_sale_page'),
    path('add_funds/', views.add_funds, name='add_funds'),
    path('confirm_complete_sale/<int:purchase_id>/', views.confirm_complete_sale, name='confirm_complete_sale'),
    path('view_sale_media/<int:purchase_id>/', views.view_sale_media, name='view_sale_media'),
    path('hide_purchase/<int:purchase_id>/', views.hide_purchase, name='hide_purchase'),
    path('delete_profile/', views.delete_profile, name='delete_profile'),
]

tenrr/models.py
from django.db import models
from django.contrib.auth.models import User
from django.conf import settings
from django.utils import timezone

class UserProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    USER_TYPE_CHOICES = (
        ('Buyer', 'Buyer'),
        ('Seller', 'Seller'),
    )
    user_type = models.CharField(max_length=6, choices=USER_TYPE_CHOICES, default='Buyer')
    contact_info = models.TextField(blank=True, null=True)
    balance = models.DecimalField(max_digits=10, decimal_places=2, default=100.00)

    def __str__(self):
        return self.user.username

class Category(models.Model):
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name

class Post(models.Model):
    title = models.CharField(max_length=200)
    content = models.TextField()
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name='posts')
    created_date = models.DateTimeField(default=timezone.now)
    category = models.ForeignKey('Category', on_delete=models.SET_NULL, null=True, blank=True)
    price = models.DecimalField(max_digits=6, decimal_places=2, default=0.00)

    def __str__(self):
        return self.title

class Like(models.Model):
    post = models.ForeignKey('Post', on_delete=models.CASCADE, related_name='likes')
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        unique_together = ('post', 'user')

class Purchase(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, related_name='purchases', on_delete=models.CASCADE)
    post = models.ForeignKey('Post', related_name='purchased_by', on_delete=models.CASCADE)
    purchase_date = models.DateTimeField(auto_now_add=True)
    buyer_note = models.TextField(blank=True, null=True)
    is_complete = models.BooleanField(default=False)
    hidden = models.BooleanField(default=False)

    def __str__(self):
        return f'{self.user.username} purchased {self.post.title}'

class PurchaseMedia(models.Model):
    purchase = models.ForeignKey('Purchase', related_name='media', on_delete=models.CASCADE)
    file = models.FileField(upload_to='purchase_media/')
    uploaded_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f'Media for Purchase {self.purchase.id}'

tenrr/forms.py
from django import forms
from django.contrib.auth.models import User
from tenrr.models import UserProfile
from .models import Post

class UserProfileForm(forms.ModelForm):
    username = forms.CharField(max_length=128, help_text="Please enter your username.")
    email = forms.EmailField(max_length=254, help_text="Please enter your email.")
    user_type = forms.ChoiceField(choices=UserProfile.USER_TYPE_CHOICES, help_text="Are you a buyer or seller?")
    contact_info = forms.CharField(widget=forms.Textarea, required=False, help_text="Please enter your contact information.")

    class Meta:
        model = User
        fields = ('username', 'email', 'user_type', 'contact_info')


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ['title', 'content', 'category', 'price']

tenrr/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.http import HttpResponse
from django.contrib.auth import authenticate, login as auth_login
from django.contrib.auth.models import User
from django.contrib import messages
from django.contrib.auth import logout
from django.contrib.auth.decorators import login_required
from django.urls import reverse
from tenrr.models import UserProfile
from tenrr.forms import UserProfileForm
from django.contrib import messages
from .forms import PostForm
from .models import Post, Category
from django.http import JsonResponse
from django.views.decorators.http import require_POST
from .models import Post, Like, Purchase
from django.db.models import Exists, OuterRef
from django.db.models import Count, Q
from .models import Category, PurchaseMedia
from django.db import transaction
from decimal import Decimal

@login_required
def my_profile(request):
    user_profile, created = UserProfile.objects.get_or_create(user=request.user)
    user_posts = Post.objects.filter(author=request.user).order_by('-created_date')
    purchased_posts = Purchase.objects.filter(user=request.user).prefetch_related('media').order_by('-purchase_date')
    sales = Purchase.objects.filter(post__author=request.user).prefetch_related('user', 'post').order_by('-purchase_date')

    context = {
        'user': request.user,
        'user_profile': user_profile,
        'user_posts': user_posts,
        'purchased_posts': purchased_posts,
        'sales': sales,
    }
    return render(request, 'tenrr/my_profile.html', context)

# Signup view
def signup_view(request):
    context_dict = {'boldmessage': 'signup'}
    if request.method == "POST":
        username = request.POST['username']
        email = request.POST['email']
        password = request.POST['password']
        confirm_password = request.POST['confirm-password']
        user_type = request.POST.get('user_type', 'Buyer')

        if password == confirm_password:
            try:
                user = User.objects.create_user(username, email, password)
                user.save()
                user_profile = UserProfile(user=user, user_type=user_type)
                user_profile.save()
                return redirect('tenrr:login') 
            except:
                messages.error(request, "Error creating user. Please try again.")
        else:
            messages.error(request, "Passwords do not match.")
    return render(request, 'tenrr/signup.html', context=context_dict)

# Login view
def login_view(request):
    context_dict = {'boldmessage': 'login'}
    if request.method == "POST":
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(request, username=username, password=password)
        if user is not None:
            auth_login(request, user)
            next_url = request.GET.get('next', 'tenrr:index') 
            return redirect(next_url)
        else:
            messages.error(request, "Invalid login details.")
    else:
        if 'next' in request.GET:
            messages.info(request, 'To make a post you must login.')

    return render(request, 'tenrr/login.html', context=context_dict)

@login_required
def logout_view(request):
    logout(request)
    return redirect(reverse('tenrr:index'))

def index(request):
    categories = Category.objects.all() 
    context_dict = {'boldmessage': 'happy', 'categories': categories}
    return render(request, 'tenrr/index.html', context=context_dict)


def about(request):
    context_dict = {'boldmessage': 'about'}
    return render(request, 'tenrr/about.html', context=context_dict)

def search(request):
    query = request.GET.get('q', '')
    category_id = request.GET.get('category', None)
    min_price = request.GET.get('min_price', None)
    max_price = request.GET.get('max_price', None)
    categories = Category.objects.all()

    posts = Post.objects.all()

    if query:
        posts = posts.filter(content__icontains=query)
    
    if category_id:
        posts = posts.filter(category_id=category_id)
    
    if min_price:
        posts = posts.filter(price__gte=min_price)
    
    if max_price:
        posts = posts.filter(price__lte=max_price)

    context = {
        'posts': posts,
        'categories': categories,
        'selected_category_id': int(category_id) if category_id else None,
    }
    return render(request, 'tenrr/search.html', context)

def search_view(request):
    user = request.user
    posts = Post.objects.all()

    category_id = request.GET.get('category', None)
    if category_id is not None:
        posts = posts.filter(category_id=category_id)

    if request.user.is_authenticated:
        likes_subquery = Like.objects.filter(user=request.user, post_id=OuterRef('pk'))
        posts = posts.annotate(user_has_liked=Exists(likes_subquery))
    else:
        posts = posts.annotate(user_has_liked=False)

    context = {'posts': posts}
    return render(request, 'search.html', context)


def recommendations(request):
    if request.user.is_authenticated:
        user = request.user
        liked_categories = Post.objects.filter(likes__user=user).values_list('category', flat=True).distinct()
        recommended_posts = Post.objects.filter(category__in=liked_categories).exclude(likes__user=user).annotate(likes_count=Count('likes')).order_by('-likes_count')[:10]
        return render(request, 'tenrr/recommendations.html', {'posts': recommended_posts})
    else:
        return render(request, 'tenrr/recommendations.html', {'login_prompt': True})



@login_required
def post(request):
    if request.method == 'POST':
        form = PostForm(request.POST)
        if form.is_valid():
            new_post = form.save(commit=False)
            new_post.author = request.user
            new_post.save()
            messages.success(request, 'Thank you for making a post')
            return redirect('tenrr:post')
    else:
        form = PostForm()
    return render(request, 'tenrr/post.html', {'form': form})

@login_required
def edit_profile(request):
    user = request.user
    user_profile, created = UserProfile.objects.get_or_create(user=user)
    if request.method == 'POST':
        form = UserProfileForm(request.POST, instance=user)
        if form.is_valid():
            user.username = form.cleaned_data['username']
            user.email = form.cleaned_data['email']
            user.save()
            user_profile.user_type = form.cleaned_data['user_type']
            user_profile.contact_info = form.cleaned_data['contact_info']
            user_profile.save()
            messages.success(request, 'Your profile was successfully updated!')
            return redirect('tenrr:my_profile')
        else:
            messages.error(request, 'Please correct the error below.')
    else:
        form = UserProfileForm(initial={'username': user.username, 'email': user.email, 'user_type': user_profile.user_type, 'contact_info': user_profile.contact_info})
    return render(request, 'tenrr/edit_profile.html', {'form': form})

def ajax_login_required(view_func):
    def _wrapped_view(request, *args, **kwargs):
        if not request.user.is_authenticated:
            return JsonResponse({'error': 'Please sign in to like a post'}, status=403)
        return view_func(request, *args, **kwargs)
    return _wrapped_view


@ajax_login_required
@require_POST
@login_required
def like_post(request, post_id):
    post = Post.objects.get(id=post_id)
    liked = False  
    like, created = Like.objects.get_or_create(post=post, user=request.user)
    
    if not created:
        like.delete()
    else:
        liked = True

    return JsonResponse({
        'likes_count': post.likes.count(),
        'liked': liked
    })

@login_required
@require_POST
def delete_post(request, post_id):
    post = get_object_or_404(Post, id=post_id, author=request.user) 
    post.delete()
    return redirect('tenrr:my_profile')

def buy_post(request, post_id):
    post = get_object_or_404(Post, id=post_id)
    return render(request, 'tenrr/buy_post.html', {'post': post})


@login_required
def confirm_purchase(request, post_id):
    if request.method == 'POST': 
        post = get_object_or_404(Post, id=post_id)
        user_profile = get_object_or_404(UserProfile, user=request.user)
        seller_profile = get_object_or_404(UserProfile, user=post.author)
        buyer_note = request.POST.get('buyer_note', '')

        if user_profile.balance < post.price:
            messages.error(request, "You do not have enough balance to make this purchase.")
            return redirect('tenrr:my_profile')

        with transaction.atomic():
            user_profile.balance -= Decimal(post.price)
            user_profile.save()

            seller_profile.balance += Decimal(post.price)
            seller_profile.save()

            purchase = Purchase.objects.create(user=request.user, post=post, buyer_note=buyer_note)
            

            messages.success(request, "Purchase successful! The cost has been deducted from your balance.")

        return redirect('tenrr:my_profile')

@login_required
def add_funds(request):
    if request.method == 'POST':
        amount = request.POST.get('amount')
        try:
            amount = Decimal(amount)
            if amount > 0:
                user_profile = UserProfile.objects.get(user=request.user)
                user_profile.balance += amount
                user_profile.save()
                messages.success(request, f'£{amount} added to your balance.')
            else:
                messages.error(request, 'Invalid amount.')
        except ValueError:
            messages.error(request, 'Invalid amount.')
        return redirect('tenrr:my_profile')
    else:
        return redirect('tenrr:my_profile')
    

@login_required
def complete_sale_page(request, purchase_id):
    purchase = get_object_or_404(Purchase, id=purchase_id)

templates/tenrr/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="Your Website Description">
    <meta name="csrf-token" content="{{ csrf_token }}">
    <title>{% block title %}Your Website Title{% endblock %}</title>
    <!-- Google Fonts -->
    <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@400;500;700&display=swap" rel="stylesheet">
    <!-- Custom CSS -->
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    {% block extra_css %}{% endblock %}
    <style>
        .messages {
            margin: 20px 0;
        }
        .alert {
            padding: 10px;
            background-color: #f4f4f4;
            border: 1px solid #ddd;
            border-radius: 5px;
            margin-bottom: 10px;
        }
        .alert-success {
            background-color: #dff0d8;
            border-color: #d6e9c6;
            color: #3c763d;
        }
        .alert-info {
            background-color: #d9edf7;
            border-color: #bce8f1;
            color: #31708f;
        }
    </style>
</head>
<body>
    <header>
        <div class="container">
            <!-- Clickable logo that redirects to the home page -->
            
            <nav>
                <ul>
                    <a href="{% url 'tenrr:index' %}">
                        <img src="{% static 'images/TenrrLogo.png' %}" alt="Tenrr Logo" id="logo" style="margin-right: 600px;">
                    </a>
                    {% if user.is_authenticated and user.userprofile.user_type == 'Seller' %}
                        <li><a href="{% url 'tenrr:post' %}">POST</a></li>
                    {% endif %}
                    <li><a href="{% url 'tenrr:search' %}">SEARCH</a></li>
                    <li><a href="{% url 'tenrr:about' %}">ABOUT</a></li>
                    <li><a href="{% url 'tenrr:recommendations' %}">RECOMMENDATIONS</a></li>
                    {% if user.is_authenticated %}
                        <li><a href="{% url 'tenrr:logout' %}">LOG OUT</a></li>
                        <li><a href="{% url 'tenrr:my_profile' %}">My Profile</a></li>
                    {% else %}
                        <li><a href="{% url 'tenrr:login' %}">LOGIN</a></li>
                        <li><a href="{% url 'tenrr:signup' %}">SIGN UP</a></li>
                    {% endif %}
                </ul>
            </nav>
        </div>
    </header>
    
    <main>
        <div class="container messages">
            {% if messages %}
                {% for message in messages %}
                    <div class="alert {{ message.tags }}">{{ message }}</div>
                {% endfor %}
            {% endif %}
        </div>
        {% block content %}{% endblock %}
    </main>
    
    <footer>
        <div class="container">
            <p>&copy; 2024 Tenrr - All Rights Reserved</p>
            <div class="social-icons">
                <!-- Consider adding social media icons here for enhanced connectivity -->
            </div>
        </div>
    </footer>
    
    <script src="{% static 'js/script.js' %}"></script>
    {% block extra_js %}{% endblock %}
</body>
</html>

templates/tenrr/buy_post.html
{% extends 'tenrr/base.html' %}
{% block title %}Buy Post{% endblock %}
{% block extra_css %}
<style>
    .buy-container {
        display: flex;
        gap: 20px;
    }
    .post-container, .details-container {
        flex: 1;
        border: 1px solid #ddd;
        box-shadow: 0 2px 4px rgba(0,0,0,.1);
        padding: 20px;
        border-radius: 5px;
        display: flex;
        flex-direction: column;
    }
    .details-header {
        margin-bottom: 10px;
    }
    .details-container textarea {
        flex-grow: 1;
        margin-top: 10px;
        border-radius: 5px;
        border: 1px solid #ccc;
        padding: 8px;
        width: 100%;
        box-sizing: border-box;
    }
    .confirm-purchase-btn-container {
        text-align: center; 
        margin-top: 20px; 
    }
    .confirm-purchase-btn {
        padding: 10px 20px;
        background-color: #4CAF50;
        color: white;
        border: none;
        border-radius: 5px;
        cursor: pointer;
        font-size: 18px; 
    }
</style>
{% endblock %}

{% block content %}
<div class="container">
    <form method="post" action="{% url 'tenrr:confirm_purchase' post.id %}">
        {% csrf_token %}
        <h1>Buy Post:</h1>
        <div class="buy-container">
            <div class="post-container">
                <h4>{{ post.title }}</h4>
                <p>{{ post.content }}</p>
                <p>Price: £{{ post.price }}</p>
                <p>Posted by: {{ post.author.username }}</p>
            </div>
            <div class="details-container">
                <h4 class="details-header">Enter any notes to seller:</h4>
                <textarea name="buyer_note" placeholder="Add any notes for the seller here" style="height: 100%;"></textarea>
            </div>
        </div>
        <div class="confirm-purchase-btn-container">
            <button type="submit" class="confirm-purchase-btn">Confirm Purchase</button>
        </div>
    </form>
</div>
{% endblock %}

templates/tenrr/index.html
{% extends 'tenrr/base.html' %}

{% block title %}Tenrr - Home Page{% endblock %}

{% block content %}
    <div class="hero">
        <h1>Browse various freelancers and their services</h1>
        <form action="{% url 'tenrr:search' %}" method="get" class="search-form">
            <input type="text" name="query" placeholder="Search services or freelancers">
            <button type="submit">Search</button>
        </form>
    </div>

    <section id="categories" class="container">
        <h2>Popular Categories</h2>
        <div class="categories-grid">
            {% for category in categories %}
                <a href="{% url 'tenrr:search' %}?category={{ category.id }}">{{ category.name }}</a>
            {% endfor %}
        </div>
    </section>
{% endblock %}

templates/tenrr/my_profile.html
{% extends 'tenrr/base.html' %}
{% block title %}My Profile{% endblock %}
{% block extra_css %}
<style>
    .profile-header-container {
        display: flex;
        justify-content: space-between;
        align-items: center;
    }
    .edit-profile-btn {
        font-size: 25px;
        padding: 5px 15px;
    }
    .profile-info, .your-posts {
        margin-bottom: 20px;
    }
    .posts-list, .sales-list {
        display: grid;
        grid-template-columns: repeat(2, 1fr);
        grid-gap: 20px;
    }
    .post, .purchase, .sale {
        position: relative; 
        border: 1px solid #ddd;
        box-shadow: 0 2px 4px rgba(0,0,0,.1);
        padding: 20px;
        border-radius: 5px;
    }
</style>
{% endblock %}

{% block content %}
<div class="container">
    <div class="profile-header-container">
        <h1>My Profile</h1>
        <a href="{% url 'tenrr:edit_profile' %}" class="btn btn-primary edit-profile-btn">Edit Profile</a>
    </div>
    <div class="profile-info">
        <p><strong>Username:</strong> {{ user.username }}</p>
        <p><strong>Email:</strong> {{ user.email }}</p>
        <p><strong>User Type:</strong> {{ user_profile.user_type }}</p>
        <p><strong>Contact Info:</strong> {{ user_profile.contact_info }}</p>
        <p><strong>Balance:</strong> £{{ user_profile.balance }}</p>
        <!-- Form to add funds -->
        <form action="{% url 'tenrr:add_funds' %}" method="post">
            {% csrf_token %}
            <div class="form-group">
                <label for="amount">Add Funds (£):</label>
                <input type="number" id="amount" name="amount" min="1" step="1" required>
                <button type="submit" class="btn btn-success">Add</button>
            </div>
        </form>
    </div>
    <div class="your-posts">
        <h2>Your Posts</h2>
        {% if user_posts %}
            <div class="posts-list">
                {% for post in user_posts %}
                    <div class="post">
                        <h3>{{ post.title }}</h3>
                        <p>{{ post.content }}</p>
                        <p>{{ post.category }}</p>
                        <p>£{{ post.price }}</p>
                        <form action="{% url 'tenrr:delete_post' post.id %}" method="post" style="display: inline;">
                            {% csrf_token %}
                            <button type="submit" class="btn btn-danger" onclick="return confirm('Are you sure you want to delete this post?');">Delete</button>
                        </form>
                    </div>
                {% endfor %}
            </div>
        {% else %}
            <p>You haven't posted anything yet.</p>
        {% endif %}
    </div>
    <div class="past-purchases">
        <h2>Past Purchases</h2>
        {% if purchased_posts %}
            <div class="posts-list">
                {% for purchase in purchased_posts %}
                    <div class="purchase">
                        <h3>{{ purchase.post.title }}</h3>
                        <p>{{ purchase.post.content }}</p>
                        <p>£{{ purchase.post.price }}</p>
                        <p>By:{{ purchase.post.author }}</p>
                        <p>Status: {% if purchase.is_complete %}Complete{% else %}Pending{% endif %}</p>
                        {% if purchase.is_complete %}
                            <a href="{% url 'tenrr:view_sale_media' purchase.id %}">View Media</a>
                        {% endif %}
                    </div>
                {% endfor %}
            </div>
        {% else %}
            <p>You haven't purchased anything yet.</p>
        {% endif %}    
    </div>
    <div class="your-sales">
        <h2>Your Sales</h2>
        {% if sales %}
            <div class="sales-list">
                {% for sale in sales %}
                    {% if not sale.hidden %}
                        <div class="sale">
                            <h3>{{ sale.post.title }}</h3>
                            <p>{{ sale.post.content }}</p>
                            <p>Bought by: {{ sale.user.username }}</p>
                            <p>Note: {{ sale.buyer_note }}</p>
                            <p>Price: £{{ sale.post.price }}</p>
                            {% if not sale.is_complete %}
                                <form action="{% url 'tenrr:complete_sale_page' sale.id %}" method="get">
                                    <button type="submit" class="btn btn-primary">Complete Sale</button>
                                </form>
                            {% endif %}
                            {% if sale.is_complete %}
                                <form action="{% url 'tenrr:hide_purchase' sale.id %}" method="post">
                                    {% csrf_token %}
                                    <button type="submit" class="btn btn-secondary">Remove Completed Sale</button>
                                </form>
                            {% endif %}
                        </div>
                    {% endif %}
                {% endfor %}
            </div>
        {% else %}
            <p>You haven't sold anything yet.</p>
        {% endif %}
    </div>
    <form action="{% url 'tenrr:delete_profile' %}" method="post" onsubmit="return confirm('Are you sure you want to delete your profile? This action cannot be undone.');">
        {% csrf_token %}
        <button type="submit" class="btn btn-danger">Delete Profile</button>
    </form>
</div>
{% endblock %}
<script>
    function deletePost(postId) {
        if (!confirm('Are you sure you want to delete this post?')) return;
        fetch(`/delete_post/${postId}/`, {
            method: 'POST',
            headers: {
                'X-CSRFToken': getCsrfToken(), 
                'Content-Type': 'application/x-www-form-urlencoded',
            },
        })
        .then(response => {
            if(response.ok) {
                return response.json();
            }
            throw new Error('Network response was not ok.');
        })
        .then(data => {
            console.log(data.message); 
            location.reload(); 
        })
        .catch(error => console.error('Error:', error));
    }
    </script>

templates/tenrr/search.html
{% extends 'tenrr/base.html' %}
{% block extra_css %}

<style>
    .posts-list {
        display: grid;
        grid-template-columns: repeat(2, 1fr);
        grid-gap: 20px;
    }
    .post {
        position: relative; 
        border: 1px solid #ddd;
        box-shadow: 0 2px 4px rgba(0,0,0,.1);
        padding: 20px;
        border-radius: 5px;
    }
    .like-container {
        position: absolute;
        top: 10px;
        right: 10px;
        display: flex;
        align-items: center;
    }
    .heart-btn {
        font-size: 24px;
        background: none;
        border: none;
        cursor: pointer;
        color: black; 
        margin-right: 5px; 
    }
    .heart-btn.liked {
        color: red; 
    }
    .buy-btn {
        position: absolute;
        bottom: 10px;
        right: 10px;
        font-size: 16px;
        padding: 5px 10px;
        background-color: #4CAF50;
        color: white;
        border: none;
        border-radius: 5px;
        text-decoration: none;
    }
</style>
{% endblock %}
{% block title %}Search{% endblock %}
{% block content %}
<div class="container">
    <h1>Search Posts</h1>
    <form method="get" action="{% url 'tenrr:search' %}">
        <input type="text" name="q" placeholder="Search for posts..." value="{{ request.GET.q }}">
        <select name="category">
            <option value="">All Categories</option>
            {% for category in categories %}
            <option value="{{ category.id }}" {% if selected_category_id == category.id %}selected{% endif %}>
                {{ category.name }}
            </option>
            {% endfor %}
        </select>
        <input type="number" name="min_price" placeholder="Min Price" value="{{ request.GET.min_price }}">
        <input type="number" name="max_price" placeholder="Max Price" value="{{ request.GET.max_price }}">
        <button type="submit">Search</button>
    </form>

    <div class="posts-list">
        {% for post in posts %}
        <div class="post">
            <h3>{{ post.title }}</h3>
            <p>{{ post.content }}</p>
            <p>Category: {{ post.category.name }}</p>
            <p>Price: £{{ post.price }}</p>
            <p>Posted by: {{ post.author.username }}</p>
            <div class="like-container">
                <button onclick="likePost({{ post.id }})" class="heart-btn {% if post.user_has_liked %}liked{% endif %}">❤</button>
                <span id="likes-count-{{ post.id }}">{{ post.likes.count }}</span>
            </div>
            {% if request.user.is_authenticated and request.user.userprofile.user_type == 'Buyer' %}
            <a href="{% url 'tenrr:buy_post' post.id %}" class="buy-btn">Buy</a>
            {% endif %}
        </div>
        {% empty %}
        <p>No posts found.</p>
        {% endfor %}
    </div>
</div>
{% endblock %}
{% block extra_js %}
<script>
    function getCsrfToken() {
        return document.querySelector('meta[name="csrf-token"]').getAttribute('content');
    }

    function likePost(postId) {
        const csrfToken = getCsrfToken();
        fetch(`/tenrr/like_post/${postId}/`, {
            method: 'POST',
            headers: {
                'X-CSRFToken': csrfToken,
                'Content-Type': 'application/json',
            },
        })
        .then(response => {
            if (!response.ok) {
                if (response.status === 403) {
                    throw new Error('Please sign in to like a post');
                } else {
                    throw new Error('Network response was not ok');
                }
            }
            return response.json();
        })
        .then(data => {
            if (data.error) {
                throw new Error(data.error);
            }
            
            document.getElementById(`likes-count-${postId}`).innerText = data.likes_count;
            
            const button = document.querySelector(`button[onclick='likePost(${postId})']`);
            if (data.liked) {
                button.classList.add('liked');
            } else {
                button.classList.remove('liked');
            }
        })
        .catch(error => {
            console.error('Error:', error);
            alert(error.message);
        });
    }
</script>
{% endblock %}